# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0003_profile_face_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(height_field='preview_width', upload_to='thumbnail', verbose_name='stream_thumbnail', width_field='preview_height')),
                ('preview_width', models.IntegerField(default=120)),
                ('preview_height', models.IntegerField(default=200)),
                ('url', models.URLField()),
                ('views', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('is_active', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Profile')),
            ],
        ),
    ]
