# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='preview_height',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='stream',
            name='preview_width',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='stream',
            name='thumbnail',
            field=models.ImageField(height_field='preview_width', upload_to='thumbnail', verbose_name='stream_thumbnail', width_field='preview_height'),
        ),
    ]
