# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_profile_face_id'),
        ('stream', '0002_auto_20160514_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='personal.Profile'),
            preserve_default=False,
        ),
    ]
