# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_profile_face_id'),
        ('stream', '0003_auto_20160515_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_time', models.IntegerField(default=0)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream.Stream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Profile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='statistics',
            unique_together=set([('stream', 'user')]),
        ),
    ]
