# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='personal.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student'), ('stranger', 'stranger')], max_length=30),
        ),
    ]
